import json
import re
import urllib.request
import time
import urllib.error

def main():
    try:
        with open('data.js', 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print("Error: data.js not found in current directory.")
        return

    cities_match = re.search(r'export const cities = \[(.*?)\];', content, re.DOTALL)
    if not cities_match:
        print("Error: Could not find cities array in data.js")
        return

    cities_str = cities_match.group(1)
    city_pattern = re.compile(r"id:\s*'([^']+)'[^}]+lat:\s*([0-9.]+)[^}]+lon:\s*([0-9.]+)")

    weather_data = {}
    
    # Try to load existing weather data so we can accumulate rather than overwrite
    try:
        with open('weather_data.js', 'r', encoding='utf-8') as wf:
            existing_content = wf.read()
            json_match = re.search(r'export const weatherData = (\{.*\});', existing_content, re.DOTALL)
            if json_match:
                weather_data = json.loads(json_match.group(1))
                print("Loaded existing historical weather data for accumulation.")
    except Exception as e:
        print(f"No existing weather data found or could not parse it, starting fresh.")

    for match in city_pattern.finditer(cities_str):
        city_id, lat, lon = match.groups()
        if float(lat) == 0.0 and float(lon) == 0.0:
            print(f"Skipping {city_id} due to 0.0 coordinates.")
            continue
        print(f"Fetching weather for {city_id} (lat:{lat}, lon:{lon})...")
        
        url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,weather_code&timezone=Asia%2FShanghai&past_days=90&forecast_days=14"
        
        max_retries = 3
        for attempt in range(max_retries):
            try:
                req = urllib.request.Request(url, headers={'User-Agent': 'Agriculture Bot'})
                with urllib.request.urlopen(req) as response:
                    data = json.loads(response.read().decode())
                    
                    dates = data['daily']['time']
                    tmax = data['daily']['temperature_2m_max']
                    tmin = data['daily']['temperature_2m_min']
                    precip = data['daily'].get('precipitation_sum', [0] * len(dates))
                    wcode = data['daily'].get('weather_code', [0] * len(dates))

                    if city_id not in weather_data:
                        weather_data[city_id] = {}
                        
                    daily_data = {}
                    for i in range(len(dates)):
                        if tmax[i] is not None and tmin[i] is not None:
                            daily_data[dates[i]] = {
                                "max": tmax[i], 
                                "min": tmin[i],
                                "precip": precip[i] if precip[i] is not None else 0,
                                "code": wcode[i] if wcode[i] is not None else 0
                            }
                            
                    # Merge new daily data into existing history
                    weather_data[city_id].update(daily_data)
                    
                    print(f" -> Successfully fetched and merged {len(daily_data)} days. Total accumulated: {len(weather_data[city_id])} days.")
                    break
            except Exception as e:
                print(f" -> Attempt {attempt + 1} failed for {city_id}: {e}")
                time.sleep(3)
        else:
            print(f"Failed to fetch {city_id} after {max_retries} attempts.")
        
        # Sleep to respect rate limits
        time.sleep(0.2)

    js_content = f"// This file is auto-generated by update_weather.py\nexport const weatherData = {json.dumps(weather_data, ensure_ascii=False, separators=(',', ':'))};"

    with open('weather_data.js', 'w', encoding='utf-8') as f:
        f.write(js_content)

    print("Weather data generated successfully at weather_data.js")

if __name__ == '__main__':
    main()
